'use client';
import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import QRCode from 'qrcode';
import { jsPDF } from 'jspdf';

type Tab='url'|'text'|'vcard';
type Shape='square'|'rounded'|'dot';
const download=(href:string,name:string)=>{const a=document.createElement('a');a.href=href;a.download=name;a.click()};
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));

export default function Home(){
 const[tab,setTab]=useState<Tab>('url'),[url,setUrl]=useState('https://alperensenel.com'),[text,setText]=useState('QR kodunu birkaç saniyede oluştur.'),[card,setCard]=useState({name:'Hüseyin Alperen',surname:'Şenel',company:'',title:'',phone:'+90 555 718 37 37',email:'alperensenel37@gmail.com',web:'alperensenel.com'});
 const[dark,setDark]=useState('#132235'),[light,setLight]=useState('#ffffff'),[size,setSize]=useState(480),[body,setBody]=useState<Shape>('rounded'),[eye,setEye]=useState<Shape>('rounded'),[ball,setBall]=useState<Shape>('dot'),[logo,setLogo]=useState<string>(''),[theme,setTheme]=useState<'light'|'dark'>('light'),[toast,setToast]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null);
 const payload=useMemo(()=>tab==='url'?(url.trim()||'https://alperensenel.com'):tab==='text'?(text||' '):`BEGIN:VCARD\nVERSION:3.0\nN:${card.surname};${card.name};;;\nFN:${card.name} ${card.surname}\nORG:${card.company}\nTITLE:${card.title}\nTEL:${card.phone}\nEMAIL:${card.email}\nURL:${card.web.startsWith('http')?card.web:`https://${card.web}`}\nEND:VCARD`,[tab,url,text,card]);
 const matrix=useMemo(()=>QRCode.create(payload,{errorCorrectionLevel:'H'}).modules,[payload]);
 const shape=(ctx:CanvasRenderingContext2D,x:number,y:number,s:number,type:Shape,color:string)=>{ctx.fillStyle=color;if(type==='dot'){ctx.beginPath();ctx.arc(x+s/2,y+s/2,s*.42,0,Math.PI*2);ctx.fill()}else if(type==='rounded'){ctx.beginPath();ctx.roundRect(x+s*.08,y+s*.08,s*.84,s*.84,s*.24);ctx.fill()}else ctx.fillRect(x,y,s,s)};
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d')!;c.width=size;c.height=size;ctx.fillStyle=light;ctx.fillRect(0,0,size,size);const count=matrix.size,margin=4,cell=size/(count+margin*2);const finder=(r:number,col:number)=>[[0,0],[0,count-7],[count-7,0]].some(([a,b])=>r>=a&&r<a+7&&col>=b&&col<b+7);for(let r=0;r<count;r++)for(let col=0;col<count;col++)if(matrix.get(r,col)&&!finder(r,col))shape(ctx,(col+margin)*cell,(r+margin)*cell,cell,body,dark);for(const[r,col]of [[0,0],[0,count-7],[count-7,0]]){const x=(col+margin)*cell,y=(r+margin)*cell,w=7*cell;ctx.fillStyle=dark;if(eye==='dot'){ctx.beginPath();ctx.arc(x+w/2,y+w/2,w/2,0,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.roundRect(x,y,w,w,eye==='rounded'?cell*1.5:0);ctx.fill()}ctx.fillStyle=light;ctx.beginPath();ctx.roundRect(x+cell,y+cell,5*cell,5*cell,eye==='rounded'?cell:0);ctx.fill();shape(ctx,x+2*cell,y+2*cell,3*cell,ball,dark)}if(logo){const img=new Image();img.onload=()=>{const w=size*.2,x=(size-w)/2;ctx.fillStyle=light;ctx.beginPath();ctx.roundRect(x-size*.012,x-size*.012,w+size*.024,w+size*.024,size*.025);ctx.fill();ctx.drawImage(img,x,x,w,w)};img.src=logo}},[matrix,size,dark,light,body,eye,ball,logo]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const pickLogo=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>setLogo(String(reader.result));reader.readAsDataURL(f)};
 const png=()=>{if(canvas.current)download(canvas.current.toDataURL('image/png'),`qr-kod-${size}px.png`)};
 const svg=()=>{const count=matrix.size,margin=4,total=count+margin*2;let modules='';for(let r=0;r<count;r++)for(let c=0;c<count;c++)if(matrix.get(r,c))modules+=`<rect x="${c+margin}" y="${r+margin}" width="1" height="1" rx="${body==='rounded'?'.25':body==='dot'?'.5':'0'}"/>`;const data=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" width="${size}" height="${size}"><rect width="100%" height="100%" fill="${esc(light)}"/><g fill="${esc(dark)}">${modules}</g></svg>`;download(URL.createObjectURL(new Blob([data],{type:'image/svg+xml'})), 'qr-kod.svg')};
 const pdf=()=>{if(!canvas.current)return;const doc=new jsPDF({unit:'mm',format:[210,210]});doc.setFillColor(light);doc.rect(0,0,210,210,'F');doc.addImage(canvas.current.toDataURL('image/png'),'PNG',20,20,170,170);doc.save('qr-kod.pdf')};
 const fields=tab==='vcard'?<div className="vcard"><div><label>Ad<input value={card.name} onChange={e=>setCard({...card,name:e.target.value})}/></label><label>Soyad<input value={card.surname} onChange={e=>setCard({...card,surname:e.target.value})}/></label></div><div><label>Firma<input value={card.company} onChange={e=>setCard({...card,company:e.target.value})}/></label><label>Pozisyon<input value={card.title} onChange={e=>setCard({...card,title:e.target.value})}/></label></div><div><label>Telefon<input value={card.phone} onChange={e=>setCard({...card,phone:e.target.value})}/></label><label>E-posta<input value={card.email} onChange={e=>setCard({...card,email:e.target.value})}/></label></div><label>Web sitesi<input value={card.web} onChange={e=>setCard({...card,web:e.target.value})}/></label></div>:<label>{tab==='url'?'Bağlantı':'Metin'}{tab==='url'?<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://ornek.com"/>:<textarea value={text} onChange={e=>setText(e.target.value)} rows={4}/>}</label>;
 return <main data-theme={theme}><header className="nav shell"><a className="brand" href="#top"><span className="logo">▦</span>QR<span>Kod</span></a><nav><a href="#tool">Oluştur</a><a href="#features">Özellikler</a><button onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Tema değiştir">{theme==='light'?'◐':'☀'}</button></nav></header>
 <section className="hero shell" id="top"><div className="hero-copy"><div className="eyebrow">ÜCRETSİZ QR KOD OLUŞTURUCU</div><h1>Fikrini tara.<br/><em>Harekete geçir.</em></h1><p>Bağlantını, metnini veya kartvizit bilgilerini paylaşılabilir bir QR koda dönüştür. Kayıt yok, sınır yok.</p><div className="trust"><span>✓ Cihazında çalışır</span><span>✓ Baskı kalitesi</span><span>✓ Tamamen ücretsiz</span></div></div>
 <div className="builder" id="tool"><div className="panel"><div className="tabs">{([['url','Bağlantı'],['text','Metin'],['vcard','Kartvizit']] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}>{label}</button>)}</div><div className="fields">{fields}</div><details open><summary>Renk ve boyut</summary><div className="control-row"><label>Kod rengi<input type="color" value={dark} onChange={e=>setDark(e.target.value)}/></label><label>Zemin<input type="color" value={light} onChange={e=>setLight(e.target.value)}/></label></div><label>Boyut <b>{size}px</b><input type="range" min="220" max="800" step="20" value={size} onChange={e=>setSize(+e.target.value)}/></label></details><details><summary>Logo</summary><label className="upload">{logo?'Logoyu değiştir':'Logo seç'}<input type="file" accept="image/png,image/jpeg,image/svg+xml" onChange={pickLogo}/></label>{logo&&<button className="remove" onClick={()=>setLogo('')}>Logoyu kaldır</button>}</details><details><summary>Şekil seçenekleri</summary>{([['Gövde şekli',body,setBody],['Göz çerçevesi',eye,setEye],['Göz bebeği',ball,setBall]] as const).map(([label,current,setter])=><div className="shape-row" key={label}><span>{label}</span><div>{(['square','rounded','dot'] as Shape[]).map(s=><button className={current===s?'active':''} onClick={()=>setter(s)} key={s} aria-label={s}><i className={s}/></button>)}</div></div>)}</details></div>
 <div className="preview"><div className="scan"><canvas ref={canvas}/></div><strong>QR kodun hazır</strong><small>Değişiklikler anında uygulanır.</small><div className="downloads"><button onClick={png}>PNG indir</button><button onClick={svg}>SVG</button><button onClick={pdf}>PDF</button></div><button className="copy-data" onClick={()=>navigator.clipboard.writeText(payload).then(()=>notify('İçerik kopyalandı'))}>QR içeriğini kopyala</button></div></div></section>
 <section className="features shell" id="features"><div><b>∞</b><h3>Sınırsız ve ücretsiz</h3><p>Üyelik veya kota olmadan dilediğin kadar QR kod oluştur.</p></div><div><b>▣</b><h3>Baskıya hazır kalite</h3><p>800 piksele kadar PNG, ölçeklenebilir SVG ve PDF indir.</p></div><div><b>◧</b><h3>Üç içerik türü</h3><p>Bağlantı, serbest metin ve vCard kartvizit desteği.</p></div><div><b>◈</b><h3>Tamamen cihazında</h3><p>Girdiğin bilgiler ve logon sunucuya gönderilmez.</p></div></section><footer>© 2026 Alperen Şenel · QR Kod</footer>{toast&&<div className="toast">✓ {toast}</div>}</main>}
